### ISSUE TITLE
Bar plot of different types of researchers

### ISSUE THREAD

**Issue by srobledog** [coreofscience/ucatolicaluisamigo_production#6]
Please create a bar plot like this 

![image](https://user-images.githubusercontent.com/8762305/161637101-3ddcf48d-7647-4089-8e21-2321ef56eada.png)

**Comment by bryanariasq02** [comment]
![image](https://user-images.githubusercontent.com/64503849/164300574-c1a963a7-3856-46f6-85df-8c669a34e549.png)
